---
name: "Spotify"
guid: "8a586678-5b5f-4a40-afaa-5db100a21b34"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net9.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "asriel"
artifacts:
  - "Jellyfin.Plugin.Spotify.dll"
changelog: >
  changelog
