---
name: "Spotify"
guid: "8a586678-5b5f-4a40-afaa-5db100a21b34"
version: "1.0.0.3"
targetAbi: "10.9.0.0"
framework: "net9.0"
overview: "Spotify metadata provider"
description: >
  Grabs track, artist, and album metadata directly from Spotify.
  Requires a valid Spotify account, but it does not need to be Premium.
category: "Music"
owner: "Asriel"
artifacts:
  - "Jellyfin.Plugin.Spotify.dll"
  - "Wavee.dll"
  - "Google.Protobuf.dll"
  - "GraphQL.Client.Abstractions.dll"
  - "GraphQL.Client.Abstractions.Websocket.dll"
  - "GraphQL.Client.dll"
  - "GraphQL.Client.Serializer.SystemTextJson.dll"
  - "GraphQL.Primitives.dll"
  - "System.Reactive.dll"
  - "System.Security.Cryptography.ProtectedData.dll"
changelog: >
  - :D
